server:
  additionalApplications:
    - name: badr-project
      namespace: default
      project: default
      source:
        # L'espace réservé sera remplacé par l'URL réelle du dépôt
        repoURL: '${ badr-project_repo }'
        path: helm/badr-     athect
        pathectevision: main
        helm:
          valueFiles:
            - values.aws.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
